### ISSUE TITLE
Error with travis-ci

### ISSUE THREAD

**Issue by ncarboni** [g-provost/lightgallery-markdown#1]
I get an error while trying to install this extension with travis-ci and I do not understand where it comes from. I wonder if you could help.

Log from travis of the installation of lightgallery-markdown:

```
running install
running bdist_egg
running egg_info
creating lightgallery.egg-info
writing requirements to lightgallery.egg-info/requires.txt
writing lightgallery.egg-info/PKG-INFO
writing top-level names to lightgallery.egg-info/top_level.txt
writing dependency_links to lightgallery.egg-info/dependency_links.txt
writing manifest file 'lightgallery.egg-info/SOURCES.txt'
reading manifest file 'lightgallery.egg-info/SOURCES.txt'
writing manifest file 'lightgallery.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying lightgallery.py -> build/lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib/lightgallery.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/lightgallery.py to lightgallery.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/lightgallery-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing lightgallery-0.1.0-py2.7.egg
Copying lightgallery-0.1.0-py2.7.egg to /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
Adding lightgallery 0.1.0 to easy-install.pth file
Installed /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/lightgallery-0.1.0-py2.7.egg
Processing dependencies for lightgallery==0.1.0
Searching for Markdown==3.0.1
Best match: Markdown 3.0.1
Adding Markdown 3.0.1 to easy-install.pth file
Installing markdown_py script to /home/travis/virtualenv/python2.7.14/bin
Using /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
Finished processing dependencies for lightgallery==0.1.0
0.26s$ mkdocs build -f ../mkdocs.yml --site-dir doks/
ERROR   -  Config value: 'markdown_extensions'. Error: configs 
Aborted with 1 Configuration Errors!
The command "mkdocs build -f ../mkdocs.yml --site-dir doks/" failed and exited with 1 during .
```

travis.yml :

```yml
env:
  global:
    secure: [//key]

language: python # Set the build language to Python

#python: 3.6 # python version

branches: master # Set the branch to build from

install:
    - pip install mkdocs # Install the required dependencies
    - pip install mkdocs-material
    - pip install pymdown-extensions
    - git clone https://github.com/g-provost/lightgallery-markdown.git
    - cd lightgallery-markdown
    - python setup.py install
    - mkdocs build -f ../mkdocs.yml --site-dir doks/
```
    
My mkdocs yml:

```yml
site_name: name
#repo_url: https://github.com/address
site_description: name

# Customization
extra:
  social:
    - type: globe
    - link: name
  

# pagination  
nav:
    - Project Home: index.md
    - Entity Reference Model:
      - Instruction: instruction.md
      - Artist : et/person.md
      - Artwork: et/artwork.md
    - Modelling Examples:
      - Instruction: pattern/instruction.md
      - Shared: pattern/general.md
      - Temporal: pattern/temporal.md
#     - Conceptual: pattern/conceptual.md
      - Physical: pattern/physical.md  
    - Ontology Extension:
      - Extension: schema.md

theme:
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  font:
    text: 'Source Sans Pro'
    code: 'IBM Plex Mono'
  custom_dir: 'theme/'
  palette:
    primary: 'white'
 
markdown_extensions:
  - pymdownx.smartsymbols
  - lightgallery
  - pymdownx.mark
  - markdown.extensions.attr_list
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - meta
  - footnotes
  - admonition
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

  

extra_css:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
  - 'stylesheets/extra.css'
extra_javascript:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
```

Any ideas?
